### ISSUE TITLE
ShapeNetPart Missing

### ISSUE THREAD

**Issue by chenbowen** [guochengqian/PointNeXt#9] opened 2022-06-22 03:27 UTC
Hi! Could you please provide the instruction and cfgs for part segmentation on ShapeNetPart? Thank you!

**Comment by guochengqian** [comment] 2022-06-22 03:37
will be released in one week

**Comment by yuchenlichuck** [comment] 2022-06-22 08:25
will be released soon, thanks for your message

**Comment by zen-d** [comment] 2022-07-11 00:12
> will be released in one week

As far as I can see, it is still not released after ~20 days?

**Comment by guochengqian** [comment] 2022-08-05 08:33
We have finished code cleaning. Sorry, it takes time because we are working on different versions of code and I have to retrain each model to make sure they can reproduce using the latest code. 
The code will be released soon when I have free time to integrate shapenetpart into the main branch.  It should take less than 1 week after the NeurIPS rebuttal.

**Comment by guochengqian** [comment] 2022-08-10 13:53
> 

As I mentioned, co-authors worked on a different codebase. I have to merge them and rerun experiments. The priority of this task is put low. keep tuned. --cheers

**Closed by guochengqian** 2022-08-10 13:53 UTC
Labels: enhancement
